# Generated by Django 4.0.3 on 2022-04-21 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fact_electr', '0003_Cambios_Pedido_Model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallepedido',
            old_name='stockID',
            new_name='stockId',
        ),
    ]
