# Generated by Django 4.0.3 on 2022-04-21 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_Agregue_Stock_Model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='precio_unitario',
            new_name='precio_diario',
        ),
    ]
